# Site Settings
name:         Android Toolbox
description:  Android Toolbox
keywords:     "Android, Toolbox"

#
baseurl: #'/'

#
paginate: 10


markdown: redcarpet

exclude:
  - assets/sass
  - work/**
  - compile
  - build
  - serve
  - push

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb